const products=[
{id:1,name:'Shah Diamond Halo Ring',cat:'rings',finish:'White Gold',mat:'Diamond',price:1250,img:'https://images.unsplash.com/photo-1605100804763-247f67b3557e?auto=format&fit=crop&w=1000&q=90',tag:'New'},
{id:2,name:'Noor Pearl Drop Earrings',cat:'earrings',finish:'Yellow Gold',mat:'Pearl',price:640,img:'https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?auto=format&fit=crop&w=1000&q=90',tag:'Best Seller'},
{id:3,name:'Solara Tennis Bracelet',cat:'bracelets',finish:'White Gold',mat:'Crystal',price:890,img:'https://images.unsplash.com/photo-1611591437281-460bfbe1220a?auto=format&fit=crop&w=1000&q=90',tag:'Limited'},
{id:4,name:'Persian Garden Pendant',cat:'necklaces',finish:'Rose Gold',mat:'Diamond',price:780,img:'https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?auto=format&fit=crop&w=1000&q=90',tag:'Signature'},
{id:5,name:'Ariana Pavé Band',cat:'rings',finish:'Rose Gold',mat:'Crystal',price:520,img:'https://images.unsplash.com/photo-1603561591411-07134e71a2a9?auto=format&fit=crop&w=1000&q=90',tag:'Gift Pick'},
{id:6,name:'Caspian Sapphire Necklace',cat:'necklaces',finish:'Yellow Gold',mat:'Sapphire',price:1380,img:'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?auto=format&fit=crop&w=1000&q=90',tag:'Luxury'},
{id:7,name:'Laleh Crystal Studs',cat:'earrings',finish:'White Gold',mat:'Crystal',price:390,img:'https://images.unsplash.com/photo-1630019852942-f89202989a59?auto=format&fit=crop&w=1000&q=90',tag:'Essential'},
{id:8,name:'Darya Gold Bangle',cat:'bracelets',finish:'Yellow Gold',mat:'Gold',price:740,img:'https://images.unsplash.com/photo-1611652022419-a9419f74343d?auto=format&fit=crop&w=1000&q=90',tag:'New'},
{id:9,name:'Ziba Emerald Signet',cat:'rings',finish:'Yellow Gold',mat:'Emerald',price:1150,img:'https://images.unsplash.com/photo-1602751584552-8ba73aad10e1?auto=format&fit=crop&w=1000&q=90',tag:'Rare'},
{id:10,name:'Roya Layered Chain',cat:'necklaces',finish:'Rose Gold',mat:'Gold',price:570,img:'https://images.unsplash.com/photo-1620656798579-1984d9e87dfc?auto=format&fit=crop&w=1000&q=90',tag:'Layering'},
{id:11,name:'Mehr Diamond Cuff',cat:'bracelets',finish:'White Gold',mat:'Diamond',price:1640,img:'https://images.unsplash.com/photo-1627293509201-7a1138d1c009?auto=format&fit=crop&w=1000&q=90',tag:'Heirloom'},
{id:12,name:'Soraya Pearl Ring',cat:'rings',finish:'Rose Gold',mat:'Pearl',price:690,img:'https://images.unsplash.com/photo-1600721391776-b5cd0e0048f9?auto=format&fit=crop&w=1000&q=90',tag:'Elegant'},
{id:13,name:'Golestan Chandelier Earrings',cat:'earrings',finish:'Yellow Gold',mat:'Crystal',price:840,img:'https://images.unsplash.com/photo-1506630448388-4e683c67ddb0?auto=format&fit=crop&w=1000&q=90',tag:'Occasion'},
{id:14,name:'Solara Eternity Ring',cat:'rings',finish:'White Gold',mat:'Diamond',price:1880,img:'https://images.unsplash.com/photo-1601121141461-9d6647bca1ed?auto=format&fit=crop&w=1000&q=90',tag:'Premium'},
{id:15,name:'Tehran Rose Chain',cat:'necklaces',finish:'Rose Gold',mat:'Gold',price:720,img:'https://images.unsplash.com/photo-1617038260897-41a1f14a8ca0?auto=format&fit=crop&w=1000&q=90',tag:'Classic'},
{id:16,name:'Mirror Palace Bracelet',cat:'bracelets',finish:'White Gold',mat:'Crystal',price:990,img:'https://images.unsplash.com/photo-1615655406736-b37c4fabf923?auto=format&fit=crop&w=1000&q=90',tag:'Sparkle'}];
const variantImages={
'White Gold':'https://images.unsplash.com/photo-1605100804763-247f67b3557e?auto=format&fit=crop&w=1200&q=90',
'Yellow Gold':'https://images.unsplash.com/photo-1602751584552-8ba73aad10e1?auto=format&fit=crop&w=1200&q=90',
'Rose Gold':'https://images.unsplash.com/photo-1603561591411-07134e71a2a9?auto=format&fit=crop&w=1200&q=90'
};
let page=1, per=8, selectedVariant='White Gold', selectedSize='', cart=JSON.parse(localStorage.getItem('solaraCart')||'[]');
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
function init(){renderRain();menu();reveal();renderProducts();renderProductDetail();updateCart();bindCheckout();}
function renderRain(){const r=$('.diamond-rain'); if(r&&!r.children.length) r.innerHTML='<i></i>'.repeat(14)}
function menu(){const t=$('.mobile-toggle'), l=$('.links'); if(t)t.onclick=()=>l.classList.toggle('open'); const bag=$('.bag-btn'); if(bag)bag.onclick=openCart; const shade=$('.shade'), close=$('.close'); if(shade)shade.onclick=closeCart; if(close)close.onclick=closeCart;}
function reveal(){const obs=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting)e.target.classList.add('show')}),{threshold:.12}); $$('.fade-up').forEach(el=>obs.observe(el));}
function selected(name){return $$(`input[name="${name}"]:checked`).map(x=>x.value)}
function renderProducts(){const grid=$('#productGrid'); if(!grid)return; let list=[...products]; const cats=selected('cat'), finishes=selected('finish'); if(cats.length)list=list.filter(p=>cats.includes(p.cat)); if(finishes.length)list=list.filter(p=>finishes.includes(p.finish)); const sort=$('#sort')?.value||'featured'; if(sort==='low')list.sort((a,b)=>a.price-b.price); if(sort==='high')list.sort((a,b)=>b.price-a.price); if(sort==='az')list.sort((a,b)=>a.name.localeCompare(b.name)); const max=Math.max(1,Math.ceil(list.length/per)); if(page>max)page=max; const slice=list.slice((page-1)*per,page*per); $('#count').textContent=`${list.length} pieces`; grid.innerHTML=slice.map(p=>card(p)).join(''); $$('.add').forEach(b=>b.onclick=()=>addCart(+b.dataset.id)); renderPages(max); $$('input[type=checkbox]').forEach(c=>c.onchange=()=>{page=1;renderProducts()}); if($('#sort'))$('#sort').onchange=()=>{page=1;renderProducts()}; const clear=$('#clearFilters'); if(clear)clear.onclick=()=>{$$('input[type=checkbox]').forEach(c=>c.checked=false);page=1;renderProducts()};}
function card(p){return `<article class="product fade-up show"><a class="product-img" href="product.html?id=${p.id}" style="background-image:url('${p.img}')"><span class="badge">${p.tag}</span><span class="view-chip">View details</span></a><div class="product-body"><h3>${p.name}</h3><div class="meta">${p.cat} • ${p.finish} • ${p.mat}</div><div class="price">$${p.price.toLocaleString()}</div><div class="product-actions"><button class="btn small add" data-id="${p.id}">Quick Buy</button><a class="btn small ghost" href="product.html?id=${p.id}">View</a></div></div></article>`}
function renderPages(max){const pag=$('#pagination'); if(!pag)return; pag.innerHTML=Array.from({length:max},(_,i)=>`<button class="page-btn ${page===i+1?'active':''}" data-page="${i+1}">${i+1}</button>`).join(''); $$('.page-btn').forEach(b=>b.onclick=()=>{page=+b.dataset.page;renderProducts();scrollTo({top:0,behavior:'smooth'})})}
function renderProductDetail(){const root=$('#productDetail'); if(!root)return; const id=Number(new URLSearchParams(location.search).get('id'))||1; const p=products.find(x=>x.id===id)||products[0]; selectedVariant=p.finish; const gallery=[p.img, variantImages['White Gold'], variantImages['Yellow Gold'], variantImages['Rose Gold']]; root.innerHTML=`<div class="pdp-gallery"><div id="zoomBox" class="zoom-box" style="background-image:url('${p.img}')"><span>Hover to zoom</span></div><div class="thumb-row">${gallery.map((g,i)=>`<button class="thumb-btn ${i===0?'active':''}" data-img="${g}" style="background-image:url('${g}')"></button>`).join('')}</div></div><div class="pdp-info"><a class="back-link" href="collections.html">← Back to collections</a><div class="eyebrow">${p.tag} • SolaraJewelly</div><h1>${p.name}</h1><p class="pdp-price">$${p.price.toLocaleString()}</p><p class="lead">A luxury piece with polished shine, Persian-inspired detailing, and a refined finish. Choose your colour and size before adding it to your bag.</p><div class="option-block"><strong>Colour</strong><div class="swatches"><button class="swatch white active" data-variant="White Gold" data-img="${variantImages['White Gold']}"></button><button class="swatch yellow" data-variant="Yellow Gold" data-img="${variantImages['Yellow Gold']}"></button><button class="swatch rose" data-variant="Rose Gold" data-img="${variantImages['Rose Gold']}"></button></div><small id="variantName">${selectedVariant}</small></div><div class="option-block"><strong>Size</strong><div class="sizes">${sizeOptions(p.cat).map(s=>`<button class="size-btn" data-size="${s}">${s}</button>`).join('')}</div></div><div class="pdp-actions"><button id="detailAdd" class="btn">Add to bag</button><button class="btn ghost" onclick="document.querySelector('#zoomBox').classList.toggle('locked')">Lock zoom</button></div><div class="care-box"><strong>Luxury details</strong><p>Includes premium SolaraJewelly packaging, polishing cloth, and care card.</p></div></div>`; bindPdp(p);}
function sizeOptions(cat){if(cat==='rings')return ['5','6','7','8','9']; if(cat==='bracelets')return ['XS','S','M','L']; if(cat==='necklaces')return ['16 in','18 in','20 in','22 in']; return ['One size'];}
function bindPdp(p){const zoom=$('#zoomBox'); $$('.thumb-btn').forEach(btn=>btn.onclick=()=>{zoom.style.backgroundImage=`url('${btn.dataset.img}')`; $$('.thumb-btn').forEach(b=>b.classList.remove('active')); btn.classList.add('active')}); $$('.swatch').forEach(btn=>btn.onclick=()=>{selectedVariant=btn.dataset.variant; $('#variantName').textContent=selectedVariant; zoom.style.backgroundImage=`url('${btn.dataset.img}')`; $$('.swatch').forEach(b=>b.classList.remove('active')); btn.classList.add('active')}); $$('.size-btn').forEach(btn=>btn.onclick=()=>{selectedSize=btn.dataset.size; $$('.size-btn').forEach(b=>b.classList.remove('active')); btn.classList.add('active')}); if(zoom){zoom.onmousemove=e=>{const r=zoom.getBoundingClientRect(); const x=((e.clientX-r.left)/r.width)*100; const y=((e.clientY-r.top)/r.height)*100; zoom.style.backgroundPosition=`${x}% ${y}%`; zoom.style.backgroundSize='210%';}; zoom.onmouseleave=()=>{if(!zoom.classList.contains('locked')){zoom.style.backgroundPosition='center'; zoom.style.backgroundSize='cover';}}} $('#detailAdd').onclick=()=>addCart(p.id, selectedVariant, selectedSize);}
function addCart(id, variant='', size=''){const p=products.find(x=>x.id===id); const key=`${id}-${variant}-${size}`; const item=cart.find(x=>x.key===key); item?item.qty++:cart.push({...p,key,variant:variant||p.finish,size:size||'Standard',qty:1}); save(); openCart();}
function save(){localStorage.setItem('solaraCart',JSON.stringify(cart));updateCart();}
function updateCart(){const count=cart.reduce((s,i)=>s+i.qty,0); const b=$('.bag-btn'); if(b)b.textContent=`Bag (${count})`; const wrap=$('.cart-items'); if(wrap){wrap.innerHTML=cart.length?cart.map(i=>`<div class="cart-row"><div class="thumb" style="background-image:url('${i.img}')"></div><div><strong>${i.name}</strong><div class="meta">${i.variant||i.finish} • Size ${i.size||'Standard'}</div><div class="meta">$${i.price.toLocaleString()}</div><div class="qty"><button onclick="chg('${i.key}',-1)">−</button><span>${i.qty}</span><button onclick="chg('${i.key}',1)">+</button></div></div><strong>$${(i.price*i.qty).toLocaleString()}</strong></div>`).join(''):'<p class="lead">Your bag is empty.</p>'; } const total=cart.reduce((s,i)=>s+i.price*i.qty,0); const el=$('#cartTotal'); if(el)el.textContent=`$${total.toLocaleString()}`; const order=$('#orderSummary'); if(order)order.innerHTML=cart.length?cart.map(i=>`<div class="cart-row"><div class="thumb" style="background-image:url('${i.img}')"></div><div>${i.name}<div class="meta">${i.variant||i.finish} • Size ${i.size||'Standard'} • Qty ${i.qty}</div></div><strong>$${(i.price*i.qty).toLocaleString()}</strong></div>`).join(''):`<p class="lead">Your checkout bag is empty. Add pieces from the collection first.</p>`; const checkoutTotal=$('#checkoutTotal'); if(checkoutTotal)checkoutTotal.textContent=`$${total.toLocaleString()}`;}
window.chg=(key,n)=>{const item=cart.find(x=>x.key===key); if(!item)return; item.qty+=n; if(item.qty<=0)cart=cart.filter(x=>x.key!==key); save();}
function openCart(){$('#drawer')?.classList.add('open')} function closeCart(){$('#drawer')?.classList.remove('open')}
function bindCheckout(){const form=$('#checkoutForm'); if(!form)return; form.onsubmit=e=>{e.preventDefault(); if(!cart.length){alert('Please add an item to your bag first.');return} localStorage.removeItem('solaraCart'); cart=[]; updateCart(); form.reset(); $('#success').textContent='Order placed successfully. This demo checkout is functioning and ready to connect to Stripe, Shopify, or another payment processor later.';}}
document.addEventListener('DOMContentLoaded',init);
